### PR TITLE
Support Changing Background Color and Opacity (Fabric)

### LINKED ISSUE #12: Ability to change background opacity/color
**Is your feature request related to a problem? Please describe.**
In dark settings the gray background is a sharper contrast and it would be nice if the opacity could be lowered so that it is less noticeable but still helps the text stand out.

**Describe the feature you'd like**
Similar to how there is a color picker for the text it would be nice if there was an ability to change the opacity of the background and possibly also the color.

**Describe alternatives you've considered**
You can disable the background completely but this is not desirable to me as I just want it to be less bright.

**Additional context**
Here is an image where you can see how bright the background seems in a dark setting
image

### PR DESCRIPTION
**Pull request by tbejos**
This adds the ability to change the Background Color and Opacity for Fabric

I am not familiar with Forge so I did not implement it there. It also seems there were other limitations with forge due to only supporting vanilla colors at the moment. Not sure how important feature parity is but it seems the Fabric version is already more feature-rich when it comes to color selection.

Closes #12 

image

### CODE REVIEW

**Comment by tbejos** [comment]
Here is an example of roughly the same image from the github issue but with lower opacity so as to contrast less

image

**Comment by tbejos** [comment]
Figured out the issue with ARGB was `valueOf` and switching to `parseUnsignedInt` works. So I switched to having a single ARGB value for background color but we can revert this change if you prefer having 2 separate fields

Screenshot 2023-03-05 222749

**Comment by Boxadactle** [comment]
I noticed you were using `Text.literal()` for the label of the text field, is there any way you could change it to a `TranslatableText` object?

**Comment by Boxadactle** [comment]
Well actually now that I look at it, all of the labels are using LiteralText objects. I'll probably change it later. This looks good!

**Comment by tbejos** [comment]
Yeah I thought to do `TranslatableText` but chose `Text.literal()` since the other ones were also that and I assumed that meant the translation files wouldn't have the right strings for different languages

**Pull request merged**
