### PR TITLE
Relax version lock

### PR DESCRIPTION
**Pull request by TheTrashCrafter**
Makes it work on 1.19.x instead of just 1.19

### CODE REVIEW

**Comment by TheTrashCrafter** [comment]
Oh, I’m only talking about Fabric, i don’t know how to do that on Forge.

**Comment by Boxadactle** [comment]
Lmao, I literally forgot to upload these files. I updated a few days ago when I updated to 1.19 😆. I'm uploading them now

**Comment by Boxadactle** [comment]
This is also probably a better way to run on all 1.19.x versions. The reason the 1.19 version is locked on 1.19 is because of chat reporting.

**Comment by TheTrashCrafter** [comment]
Does Chat Reporting affect the coordinates Mod?

**Comment by Boxadactle** [comment]
Sending a chat message in fabric and forge was changed because of chat reporting/signing, and this mod can send your location in chat

**Comment by TheTrashCrafter** [comment]
Oh, i forgot that feature, i mainly use the hud, sorry.

**Pull request merged**
